library(RColorBrewer)
library(packcircles)
library(ggfittext) # to fit text in a box
library(emojifont)
library(extrafont)
library(extrafontdb)
library(waffle)
#library(treemap)
library(treemapify)
library(wordcloud2)
library(ggforce)
library(ggimage)
library(networkD3)
library(ggalluvial)